// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protos/justjoew.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllSectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AspectRatio   uint32                 `protobuf:"varint,1,opt,name=aspectRatio,proto3" json:"aspectRatio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSectionsRequest) Reset() {
	*x = GetAllSectionsRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSectionsRequest) ProtoMessage() {}

func (x *GetAllSectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSectionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllSectionsRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllSectionsRequest) GetAspectRatio() uint32 {
	if x != nil {
		return x.AspectRatio
	}
	return 0
}

type GetAllSectionsResonse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSectionsResonse) Reset() {
	*x = GetAllSectionsResonse{}
	mi := &file_protos_justjoew_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSectionsResonse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSectionsResonse) ProtoMessage() {}

func (x *GetAllSectionsResonse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSectionsResonse.ProtoReflect.Descriptor instead.
func (*GetAllSectionsResonse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllSectionsResonse) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AssetList     []*Asset               `protobuf:"bytes,3,rep,name=assetList,proto3" json:"assetList,omitempty"`
	SectionUrl    string                 `protobuf:"bytes,4,opt,name=sectionUrl,proto3" json:"sectionUrl,omitempty"`
	OrderIndex    uint32                 `protobuf:"varint,5,opt,name=orderIndex,proto3" json:"orderIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_protos_justjoew_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{2}
}

func (x *Section) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Section) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Section) GetAssetList() []*Asset {
	if x != nil {
		return x.AssetList
	}
	return nil
}

func (x *Section) GetSectionUrl() string {
	if x != nil {
		return x.SectionUrl
	}
	return ""
}

func (x *Section) GetOrderIndex() uint32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type CreateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SectionURL    string                 `protobuf:"bytes,2,opt,name=sectionURL,proto3" json:"sectionURL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionRequest) Reset() {
	*x = CreateSectionRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionRequest) ProtoMessage() {}

func (x *CreateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSectionRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSectionRequest) GetSectionURL() string {
	if x != nil {
		return x.SectionURL
	}
	return ""
}

type CreateSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *Section               `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionResponse) Reset() {
	*x = CreateSectionResponse{}
	mi := &file_protos_justjoew_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionResponse) ProtoMessage() {}

func (x *CreateSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionResponse.ProtoReflect.Descriptor instead.
func (*CreateSectionResponse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSectionResponse) GetSection() *Section {
	if x != nil {
		return x.Section
	}
	return nil
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionName   string                 `protobuf:"bytes,2,opt,name=sectionName,proto3" json:"sectionName,omitempty"`
	BlobPath      string                 `protobuf:"bytes,3,opt,name=blobPath,proto3" json:"blobPath,omitempty"`
	OrderIndex    uint32                 `protobuf:"varint,4,opt,name=orderIndex,proto3" json:"orderIndex,omitempty"`
	SectionId     uint32                 `protobuf:"varint,5,opt,name=sectionId,proto3" json:"sectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_protos_justjoew_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{5}
}

func (x *Asset) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Asset) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *Asset) GetBlobPath() string {
	if x != nil {
		return x.BlobPath
	}
	return ""
}

func (x *Asset) GetOrderIndex() uint32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Asset) GetSectionId() uint32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

// The request message containing the user's name.
type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     uint32                 `protobuf:"varint,1,opt,name=sectionId,proto3" json:"sectionId,omitempty"`
	Blob          []byte                 `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAssetRequest) GetSectionId() uint32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *CreateAssetRequest) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *CreateAssetRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// The response message containing the greetings
type CreateAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetResponse) Reset() {
	*x = CreateAssetResponse{}
	mi := &file_protos_justjoew_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetResponse) ProtoMessage() {}

func (x *CreateAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetResponse.ProtoReflect.Descriptor instead.
func (*CreateAssetResponse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type UpdateAssetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderIndex    uint32                 `protobuf:"varint,2,opt,name=orderIndex,proto3" json:"orderIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetOrderRequest) Reset() {
	*x = UpdateAssetOrderRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetOrderRequest) ProtoMessage() {}

func (x *UpdateAssetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetOrderRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAssetOrderRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAssetOrderRequest) GetOrderIndex() uint32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type UpdateSectionOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderIndex    uint32                 `protobuf:"varint,2,opt,name=orderIndex,proto3" json:"orderIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionOrderRequest) Reset() {
	*x = UpdateSectionOrderRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionOrderRequest) ProtoMessage() {}

func (x *UpdateSectionOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateSectionOrderRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSectionOrderRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSectionOrderRequest) GetOrderIndex() uint32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type UpdateSectionOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewOrderIndex uint32                 `protobuf:"varint,1,opt,name=newOrderIndex,proto3" json:"newOrderIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionOrderResponse) Reset() {
	*x = UpdateSectionOrderResponse{}
	mi := &file_protos_justjoew_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionOrderResponse) ProtoMessage() {}

func (x *UpdateSectionOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateSectionOrderResponse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSectionOrderResponse) GetNewOrderIndex() uint32 {
	if x != nil {
		return x.NewOrderIndex
	}
	return 0
}

type UpdateSectionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionName   string                 `protobuf:"bytes,2,opt,name=sectionName,proto3" json:"sectionName,omitempty"`
	SectionUrl    string                 `protobuf:"bytes,3,opt,name=sectionUrl,proto3" json:"sectionUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionInfoRequest) Reset() {
	*x = UpdateSectionInfoRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionInfoRequest) ProtoMessage() {}

func (x *UpdateSectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateSectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSectionInfoRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSectionInfoRequest) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *UpdateSectionInfoRequest) GetSectionUrl() string {
	if x != nil {
		return x.SectionUrl
	}
	return ""
}

type UpdateSectionInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionName   string                 `protobuf:"bytes,1,opt,name=sectionName,proto3" json:"sectionName,omitempty"`
	SectionUrl    string                 `protobuf:"bytes,2,opt,name=sectionUrl,proto3" json:"sectionUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionInfoResponse) Reset() {
	*x = UpdateSectionInfoResponse{}
	mi := &file_protos_justjoew_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionInfoResponse) ProtoMessage() {}

func (x *UpdateSectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateSectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSectionInfoResponse) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *UpdateSectionInfoResponse) GetSectionUrl() string {
	if x != nil {
		return x.SectionUrl
	}
	return ""
}

type UpdateAssetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewOrderIndex uint32                 `protobuf:"varint,1,opt,name=newOrderIndex,proto3" json:"newOrderIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetOrderResponse) Reset() {
	*x = UpdateAssetOrderResponse{}
	mi := &file_protos_justjoew_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetOrderResponse) ProtoMessage() {}

func (x *UpdateAssetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateAssetOrderResponse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateAssetOrderResponse) GetNewOrderIndex() uint32 {
	if x != nil {
		return x.NewOrderIndex
	}
	return 0
}

type DeleteSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSectionResponse) Reset() {
	*x = DeleteSectionResponse{}
	mi := &file_protos_justjoew_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSectionResponse) ProtoMessage() {}

func (x *DeleteSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSectionResponse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{14}
}

type DeleteSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     uint32                 `protobuf:"varint,1,opt,name=sectionId,proto3" json:"sectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSectionRequest) Reset() {
	*x = DeleteSectionRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSectionRequest) ProtoMessage() {}

func (x *DeleteSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSectionRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSectionRequest) GetSectionId() uint32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       uint32                 `protobuf:"varint,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteAssetRequest) GetAssetId() uint32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

type DeleteAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetResponse) Reset() {
	*x = DeleteAssetResponse{}
	mi := &file_protos_justjoew_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetResponse) ProtoMessage() {}

func (x *DeleteAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssetResponse) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{17}
}

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_protos_justjoew_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{18}
}

func (x *SendEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protos_justjoew_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_justjoew_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_justjoew_proto_rawDescGZIP(), []int{19}
}

var File_protos_justjoew_proto protoreflect.FileDescriptor

const file_protos_justjoew_proto_rawDesc = "" +
	"\n" +
	"\x15protos/justjoew.proto\x12\x0fjustjoew.asstes\"9\n" +
	"\x15GetAllSectionsRequest\x12 \n" +
	"\vaspectRatio\x18\x01 \x01(\rR\vaspectRatio\"M\n" +
	"\x15GetAllSectionsResonse\x124\n" +
	"\bsections\x18\x01 \x03(\v2\x18.justjoew.asstes.SectionR\bsections\"\xa3\x01\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\tassetList\x18\x03 \x03(\v2\x16.justjoew.asstes.AssetR\tassetList\x12\x1e\n" +
	"\n" +
	"sectionUrl\x18\x04 \x01(\tR\n" +
	"sectionUrl\x12\x1e\n" +
	"\n" +
	"orderIndex\x18\x05 \x01(\rR\n" +
	"orderIndex\"J\n" +
	"\x14CreateSectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"sectionURL\x18\x02 \x01(\tR\n" +
	"sectionURL\"K\n" +
	"\x15CreateSectionResponse\x122\n" +
	"\asection\x18\x01 \x01(\v2\x18.justjoew.asstes.SectionR\asection\"\x93\x01\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vsectionName\x18\x02 \x01(\tR\vsectionName\x12\x1a\n" +
	"\bblobPath\x18\x03 \x01(\tR\bblobPath\x12\x1e\n" +
	"\n" +
	"orderIndex\x18\x04 \x01(\rR\n" +
	"orderIndex\x12\x1c\n" +
	"\tsectionId\x18\x05 \x01(\rR\tsectionId\"b\n" +
	"\x12CreateAssetRequest\x12\x1c\n" +
	"\tsectionId\x18\x01 \x01(\rR\tsectionId\x12\x12\n" +
	"\x04blob\x18\x02 \x01(\fR\x04blob\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"C\n" +
	"\x13CreateAssetResponse\x12,\n" +
	"\x05asset\x18\x01 \x01(\v2\x16.justjoew.asstes.AssetR\x05asset\"I\n" +
	"\x17UpdateAssetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\n" +
	"orderIndex\x18\x02 \x01(\rR\n" +
	"orderIndex\"K\n" +
	"\x19UpdateSectionOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\n" +
	"orderIndex\x18\x02 \x01(\rR\n" +
	"orderIndex\"B\n" +
	"\x1aUpdateSectionOrderResponse\x12$\n" +
	"\rnewOrderIndex\x18\x01 \x01(\rR\rnewOrderIndex\"l\n" +
	"\x18UpdateSectionInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vsectionName\x18\x02 \x01(\tR\vsectionName\x12\x1e\n" +
	"\n" +
	"sectionUrl\x18\x03 \x01(\tR\n" +
	"sectionUrl\"]\n" +
	"\x19UpdateSectionInfoResponse\x12 \n" +
	"\vsectionName\x18\x01 \x01(\tR\vsectionName\x12\x1e\n" +
	"\n" +
	"sectionUrl\x18\x02 \x01(\tR\n" +
	"sectionUrl\"@\n" +
	"\x18UpdateAssetOrderResponse\x12$\n" +
	"\rnewOrderIndex\x18\x01 \x01(\rR\rnewOrderIndex\"\x17\n" +
	"\x15DeleteSectionResponse\"4\n" +
	"\x14DeleteSectionRequest\x12\x1c\n" +
	"\tsectionId\x18\x01 \x01(\rR\tsectionId\".\n" +
	"\x12DeleteAssetRequest\x12\x18\n" +
	"\aassetId\x18\x01 \x01(\rR\aassetId\"\x15\n" +
	"\x13DeleteAssetResponse\"p\n" +
	"\x10SendEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\a\n" +
	"\x05Empty2\x85\a\n" +
	"\x0fAssetController\x12b\n" +
	"\x0eGetAllSections\x12&.justjoew.asstes.GetAllSectionsRequest\x1a&.justjoew.asstes.GetAllSectionsResonse\"\x00\x12`\n" +
	"\rCreateSection\x12%.justjoew.asstes.CreateSectionRequest\x1a&.justjoew.asstes.CreateSectionResponse\"\x00\x12Z\n" +
	"\vCreateAsset\x12#.justjoew.asstes.CreateAssetRequest\x1a$.justjoew.asstes.CreateAssetResponse\"\x00\x12i\n" +
	"\x10UpdateAssetOrder\x12(.justjoew.asstes.UpdateAssetOrderRequest\x1a).justjoew.asstes.UpdateAssetOrderResponse\"\x00\x12`\n" +
	"\rDeleteSection\x12%.justjoew.asstes.DeleteSectionRequest\x1a&.justjoew.asstes.DeleteSectionResponse\"\x00\x12Z\n" +
	"\vDeleteAsset\x12#.justjoew.asstes.DeleteAssetRequest\x1a$.justjoew.asstes.DeleteAssetResponse\"\x00\x12l\n" +
	"\x11UpdateSectionInfo\x12).justjoew.asstes.UpdateSectionInfoRequest\x1a*.justjoew.asstes.UpdateSectionInfoResponse\"\x00\x12o\n" +
	"\x12UpdateSectionOrder\x12*.justjoew.asstes.UpdateSectionOrderRequest\x1a+.justjoew.asstes.UpdateSectionOrderResponse\"\x00\x12H\n" +
	"\tSendEmail\x12!.justjoew.asstes.SendEmailRequest\x1a\x16.justjoew.asstes.Empty\"\x00B\x19Z\x17justjoew/backend/protosb\x06proto3"

var (
	file_protos_justjoew_proto_rawDescOnce sync.Once
	file_protos_justjoew_proto_rawDescData []byte
)

func file_protos_justjoew_proto_rawDescGZIP() []byte {
	file_protos_justjoew_proto_rawDescOnce.Do(func() {
		file_protos_justjoew_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_justjoew_proto_rawDesc), len(file_protos_justjoew_proto_rawDesc)))
	})
	return file_protos_justjoew_proto_rawDescData
}

var file_protos_justjoew_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_protos_justjoew_proto_goTypes = []any{
	(*GetAllSectionsRequest)(nil),      // 0: justjoew.asstes.GetAllSectionsRequest
	(*GetAllSectionsResonse)(nil),      // 1: justjoew.asstes.GetAllSectionsResonse
	(*Section)(nil),                    // 2: justjoew.asstes.Section
	(*CreateSectionRequest)(nil),       // 3: justjoew.asstes.CreateSectionRequest
	(*CreateSectionResponse)(nil),      // 4: justjoew.asstes.CreateSectionResponse
	(*Asset)(nil),                      // 5: justjoew.asstes.Asset
	(*CreateAssetRequest)(nil),         // 6: justjoew.asstes.CreateAssetRequest
	(*CreateAssetResponse)(nil),        // 7: justjoew.asstes.CreateAssetResponse
	(*UpdateAssetOrderRequest)(nil),    // 8: justjoew.asstes.UpdateAssetOrderRequest
	(*UpdateSectionOrderRequest)(nil),  // 9: justjoew.asstes.UpdateSectionOrderRequest
	(*UpdateSectionOrderResponse)(nil), // 10: justjoew.asstes.UpdateSectionOrderResponse
	(*UpdateSectionInfoRequest)(nil),   // 11: justjoew.asstes.UpdateSectionInfoRequest
	(*UpdateSectionInfoResponse)(nil),  // 12: justjoew.asstes.UpdateSectionInfoResponse
	(*UpdateAssetOrderResponse)(nil),   // 13: justjoew.asstes.UpdateAssetOrderResponse
	(*DeleteSectionResponse)(nil),      // 14: justjoew.asstes.DeleteSectionResponse
	(*DeleteSectionRequest)(nil),       // 15: justjoew.asstes.DeleteSectionRequest
	(*DeleteAssetRequest)(nil),         // 16: justjoew.asstes.DeleteAssetRequest
	(*DeleteAssetResponse)(nil),        // 17: justjoew.asstes.DeleteAssetResponse
	(*SendEmailRequest)(nil),           // 18: justjoew.asstes.SendEmailRequest
	(*Empty)(nil),                      // 19: justjoew.asstes.Empty
}
var file_protos_justjoew_proto_depIdxs = []int32{
	2,  // 0: justjoew.asstes.GetAllSectionsResonse.sections:type_name -> justjoew.asstes.Section
	5,  // 1: justjoew.asstes.Section.assetList:type_name -> justjoew.asstes.Asset
	2,  // 2: justjoew.asstes.CreateSectionResponse.section:type_name -> justjoew.asstes.Section
	5,  // 3: justjoew.asstes.CreateAssetResponse.asset:type_name -> justjoew.asstes.Asset
	0,  // 4: justjoew.asstes.AssetController.GetAllSections:input_type -> justjoew.asstes.GetAllSectionsRequest
	3,  // 5: justjoew.asstes.AssetController.CreateSection:input_type -> justjoew.asstes.CreateSectionRequest
	6,  // 6: justjoew.asstes.AssetController.CreateAsset:input_type -> justjoew.asstes.CreateAssetRequest
	8,  // 7: justjoew.asstes.AssetController.UpdateAssetOrder:input_type -> justjoew.asstes.UpdateAssetOrderRequest
	15, // 8: justjoew.asstes.AssetController.DeleteSection:input_type -> justjoew.asstes.DeleteSectionRequest
	16, // 9: justjoew.asstes.AssetController.DeleteAsset:input_type -> justjoew.asstes.DeleteAssetRequest
	11, // 10: justjoew.asstes.AssetController.UpdateSectionInfo:input_type -> justjoew.asstes.UpdateSectionInfoRequest
	9,  // 11: justjoew.asstes.AssetController.UpdateSectionOrder:input_type -> justjoew.asstes.UpdateSectionOrderRequest
	18, // 12: justjoew.asstes.AssetController.SendEmail:input_type -> justjoew.asstes.SendEmailRequest
	1,  // 13: justjoew.asstes.AssetController.GetAllSections:output_type -> justjoew.asstes.GetAllSectionsResonse
	4,  // 14: justjoew.asstes.AssetController.CreateSection:output_type -> justjoew.asstes.CreateSectionResponse
	7,  // 15: justjoew.asstes.AssetController.CreateAsset:output_type -> justjoew.asstes.CreateAssetResponse
	13, // 16: justjoew.asstes.AssetController.UpdateAssetOrder:output_type -> justjoew.asstes.UpdateAssetOrderResponse
	14, // 17: justjoew.asstes.AssetController.DeleteSection:output_type -> justjoew.asstes.DeleteSectionResponse
	17, // 18: justjoew.asstes.AssetController.DeleteAsset:output_type -> justjoew.asstes.DeleteAssetResponse
	12, // 19: justjoew.asstes.AssetController.UpdateSectionInfo:output_type -> justjoew.asstes.UpdateSectionInfoResponse
	10, // 20: justjoew.asstes.AssetController.UpdateSectionOrder:output_type -> justjoew.asstes.UpdateSectionOrderResponse
	19, // 21: justjoew.asstes.AssetController.SendEmail:output_type -> justjoew.asstes.Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_justjoew_proto_init() }
func file_protos_justjoew_proto_init() {
	if File_protos_justjoew_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_justjoew_proto_rawDesc), len(file_protos_justjoew_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_justjoew_proto_goTypes,
		DependencyIndexes: file_protos_justjoew_proto_depIdxs,
		MessageInfos:      file_protos_justjoew_proto_msgTypes,
	}.Build()
	File_protos_justjoew_proto = out.File
	file_protos_justjoew_proto_goTypes = nil
	file_protos_justjoew_proto_depIdxs = nil
}
