// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/justjoew.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetController_GetAllSections_FullMethodName     = "/justjoew.asstes.AssetController/GetAllSections"
	AssetController_CreateSection_FullMethodName      = "/justjoew.asstes.AssetController/CreateSection"
	AssetController_CreateAsset_FullMethodName        = "/justjoew.asstes.AssetController/CreateAsset"
	AssetController_UpdateAssetOrder_FullMethodName   = "/justjoew.asstes.AssetController/UpdateAssetOrder"
	AssetController_DeleteSection_FullMethodName      = "/justjoew.asstes.AssetController/DeleteSection"
	AssetController_DeleteAsset_FullMethodName        = "/justjoew.asstes.AssetController/DeleteAsset"
	AssetController_UpdateSectionInfo_FullMethodName  = "/justjoew.asstes.AssetController/UpdateSectionInfo"
	AssetController_UpdateSectionOrder_FullMethodName = "/justjoew.asstes.AssetController/UpdateSectionOrder"
	AssetController_SendEmail_FullMethodName          = "/justjoew.asstes.AssetController/SendEmail"
)

// AssetControllerClient is the client API for AssetController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetControllerClient interface {
	GetAllSections(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetAllSectionsResonse, error)
	CreateSection(ctx context.Context, in *CreateSectionRequest, opts ...grpc.CallOption) (*CreateSectionResponse, error)
	CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error)
	UpdateAssetOrder(ctx context.Context, in *UpdateAssetOrderRequest, opts ...grpc.CallOption) (*UpdateAssetOrderResponse, error)
	DeleteSection(ctx context.Context, in *DeleteSectionRequest, opts ...grpc.CallOption) (*DeleteSectionResponse, error)
	DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*DeleteAssetResponse, error)
	UpdateSectionInfo(ctx context.Context, in *UpdateSectionInfoRequest, opts ...grpc.CallOption) (*UpdateSectionInfoResponse, error)
	UpdateSectionOrder(ctx context.Context, in *UpdateSectionOrderRequest, opts ...grpc.CallOption) (*UpdateSectionOrderResponse, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*Empty, error)
}

type assetControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetControllerClient(cc grpc.ClientConnInterface) AssetControllerClient {
	return &assetControllerClient{cc}
}

func (c *assetControllerClient) GetAllSections(ctx context.Context, in *GetAllSectionsRequest, opts ...grpc.CallOption) (*GetAllSectionsResonse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSectionsResonse)
	err := c.cc.Invoke(ctx, AssetController_GetAllSections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) CreateSection(ctx context.Context, in *CreateSectionRequest, opts ...grpc.CallOption) (*CreateSectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSectionResponse)
	err := c.cc.Invoke(ctx, AssetController_CreateSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssetResponse)
	err := c.cc.Invoke(ctx, AssetController_CreateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) UpdateAssetOrder(ctx context.Context, in *UpdateAssetOrderRequest, opts ...grpc.CallOption) (*UpdateAssetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssetOrderResponse)
	err := c.cc.Invoke(ctx, AssetController_UpdateAssetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) DeleteSection(ctx context.Context, in *DeleteSectionRequest, opts ...grpc.CallOption) (*DeleteSectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSectionResponse)
	err := c.cc.Invoke(ctx, AssetController_DeleteSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*DeleteAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssetResponse)
	err := c.cc.Invoke(ctx, AssetController_DeleteAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) UpdateSectionInfo(ctx context.Context, in *UpdateSectionInfoRequest, opts ...grpc.CallOption) (*UpdateSectionInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSectionInfoResponse)
	err := c.cc.Invoke(ctx, AssetController_UpdateSectionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) UpdateSectionOrder(ctx context.Context, in *UpdateSectionOrderRequest, opts ...grpc.CallOption) (*UpdateSectionOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSectionOrderResponse)
	err := c.cc.Invoke(ctx, AssetController_UpdateSectionOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetControllerClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AssetController_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetControllerServer is the server API for AssetController service.
// All implementations must embed UnimplementedAssetControllerServer
// for forward compatibility.
type AssetControllerServer interface {
	GetAllSections(context.Context, *GetAllSectionsRequest) (*GetAllSectionsResonse, error)
	CreateSection(context.Context, *CreateSectionRequest) (*CreateSectionResponse, error)
	CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error)
	UpdateAssetOrder(context.Context, *UpdateAssetOrderRequest) (*UpdateAssetOrderResponse, error)
	DeleteSection(context.Context, *DeleteSectionRequest) (*DeleteSectionResponse, error)
	DeleteAsset(context.Context, *DeleteAssetRequest) (*DeleteAssetResponse, error)
	UpdateSectionInfo(context.Context, *UpdateSectionInfoRequest) (*UpdateSectionInfoResponse, error)
	UpdateSectionOrder(context.Context, *UpdateSectionOrderRequest) (*UpdateSectionOrderResponse, error)
	SendEmail(context.Context, *SendEmailRequest) (*Empty, error)
	mustEmbedUnimplementedAssetControllerServer()
}

// UnimplementedAssetControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetControllerServer struct{}

func (UnimplementedAssetControllerServer) GetAllSections(context.Context, *GetAllSectionsRequest) (*GetAllSectionsResonse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSections not implemented")
}
func (UnimplementedAssetControllerServer) CreateSection(context.Context, *CreateSectionRequest) (*CreateSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSection not implemented")
}
func (UnimplementedAssetControllerServer) CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAsset not implemented")
}
func (UnimplementedAssetControllerServer) UpdateAssetOrder(context.Context, *UpdateAssetOrderRequest) (*UpdateAssetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssetOrder not implemented")
}
func (UnimplementedAssetControllerServer) DeleteSection(context.Context, *DeleteSectionRequest) (*DeleteSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSection not implemented")
}
func (UnimplementedAssetControllerServer) DeleteAsset(context.Context, *DeleteAssetRequest) (*DeleteAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAsset not implemented")
}
func (UnimplementedAssetControllerServer) UpdateSectionInfo(context.Context, *UpdateSectionInfoRequest) (*UpdateSectionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSectionInfo not implemented")
}
func (UnimplementedAssetControllerServer) UpdateSectionOrder(context.Context, *UpdateSectionOrderRequest) (*UpdateSectionOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSectionOrder not implemented")
}
func (UnimplementedAssetControllerServer) SendEmail(context.Context, *SendEmailRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedAssetControllerServer) mustEmbedUnimplementedAssetControllerServer() {}
func (UnimplementedAssetControllerServer) testEmbeddedByValue()                         {}

// UnsafeAssetControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetControllerServer will
// result in compilation errors.
type UnsafeAssetControllerServer interface {
	mustEmbedUnimplementedAssetControllerServer()
}

func RegisterAssetControllerServer(s grpc.ServiceRegistrar, srv AssetControllerServer) {
	// If the following call pancis, it indicates UnimplementedAssetControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetController_ServiceDesc, srv)
}

func _AssetController_GetAllSections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).GetAllSections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_GetAllSections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).GetAllSections(ctx, req.(*GetAllSectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_CreateSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).CreateSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_CreateSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).CreateSection(ctx, req.(*CreateSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_CreateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).CreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_UpdateAssetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).UpdateAssetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_UpdateAssetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).UpdateAssetOrder(ctx, req.(*UpdateAssetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_DeleteSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).DeleteSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_DeleteSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).DeleteSection(ctx, req.(*DeleteSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_DeleteAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).DeleteAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_DeleteAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).DeleteAsset(ctx, req.(*DeleteAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_UpdateSectionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSectionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).UpdateSectionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_UpdateSectionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).UpdateSectionInfo(ctx, req.(*UpdateSectionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_UpdateSectionOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSectionOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).UpdateSectionOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_UpdateSectionOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).UpdateSectionOrder(ctx, req.(*UpdateSectionOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetController_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetControllerServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetController_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetControllerServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetController_ServiceDesc is the grpc.ServiceDesc for AssetController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "justjoew.asstes.AssetController",
	HandlerType: (*AssetControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllSections",
			Handler:    _AssetController_GetAllSections_Handler,
		},
		{
			MethodName: "CreateSection",
			Handler:    _AssetController_CreateSection_Handler,
		},
		{
			MethodName: "CreateAsset",
			Handler:    _AssetController_CreateAsset_Handler,
		},
		{
			MethodName: "UpdateAssetOrder",
			Handler:    _AssetController_UpdateAssetOrder_Handler,
		},
		{
			MethodName: "DeleteSection",
			Handler:    _AssetController_DeleteSection_Handler,
		},
		{
			MethodName: "DeleteAsset",
			Handler:    _AssetController_DeleteAsset_Handler,
		},
		{
			MethodName: "UpdateSectionInfo",
			Handler:    _AssetController_UpdateSectionInfo_Handler,
		},
		{
			MethodName: "UpdateSectionOrder",
			Handler:    _AssetController_UpdateSectionOrder_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _AssetController_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/justjoew.proto",
}
