name: justjoew
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gif: ^2.3.0
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Black.ttf
          weight: 900
        - asset: fonts/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: fonts/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SourceCodePro-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts/SourceCodePro-Italic.ttf
          style: italic
        - asset: fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: fonts/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: fonts/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SourceCodePro-VariableFont_wght.ttf
