name: justjoew
description: "JustJoew a digital artist"
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7
  getwidget: ^2.0.4
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.6
  gif: ^2.3.0
  go_router: ^14.2.0
  sticky_footer_scrollview: ^1.1.1
  flutter_displaymode: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro/SourceCodePro-Black.ttf
          weight: 900
        - asset: fonts/SourceCodePro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: fonts/SourceCodePro/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceCodePro/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-Italic.ttf
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-Light.ttf
          weight: 300
        - asset: fonts/SourceCodePro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: fonts/SourceCodePro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceCodePro/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SourceCodePro/SourceCodePro-VariableFont_wght.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
