name: Build and Push Docker image

on:
  push:
    paths:
      - 'ClippyClips/**'
      - '.github/workflows/docker-publish-joew-clips.yml'
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build and push Docker  image
      uses: docker/build-push-action@v3
      with:
        context: ./ClippyClips
        file: ./ClippyClips/Dockerfile
        push: true
        tags: ghcr.io/ntthyssen/justjoew_clips:latest 
   # - name: Run curl command
   #   if: github.ref == 'refs/heads/master'
   #   run: |
   #     curl -X POST "http://z-signal.net:9301/deploy?servicename=clips"
    