version: '3.9'

services:
  go_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - envoy_network

  envoy:
    image: envoyproxy/envoy:v1.20.0
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "9902:9902"
    networks:
      - envoy_network
    depends_on:
      - go_server

networks:
  envoy_network:
    driver: bridge